baseurl = "/"
title = "Yet Another Geographer"
copyright = ""
languageCode = "en-US"
canonifyurls = true
paginate = 3
theme = "dusk"

googleAnalytics = ""
disqusShortname = ""

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "monokai" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

#[[menu.main]]
#  name = "Posts"
#  weight = -120
#  identifier = "post"
#  url = "/posts/"

#[[menu.main]]
#  name = "Tags"
#  weight = -110
#  identifier = "tag"
#  url = "/tags/"

[[menu.main]]
    name = "About | "
    weight = -200
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = " CV |  "
    weight = -190
    identifier = "cv"
    url = "https://www.dropbox.com/s/y5mjkduq7bopzex/currvita.pdf?dl=0"

[[menu.main]]
    name = " Bristol |  "
    weight = -180
    identifier = "brizzle"
    url = "http://www.bristol.ac.uk/geography/people/levi-j-wolf/overview.html"

[[menu.main]]
    name = " Chicago |  "
    weight = -170
    identifier = "uchicago"
    url = "https://spatial.uchicago.edu"

[[menu.main]]
    name = " UCR |  "
    weight = -160
    identifier = "ucr"
    url = "https://spatial.ucr.edu"

[[menu.main]]
    name = " Talks | "
    weight = -150
    identifier = "talks"
    url = "/talks/"

[author]
  name = "Levi John Wolf"

[params.meta]
  keywords = ""
  description = "just a geograblog"

[params]
  email = "levi.john.wolf@gmail.com"
  github = "ljwolf"
  #gitlab = "gitlab id"
  twitter = "levijohnwolf"
  job = "https://bristol.ac.uk/geography/"
  #linkedin = "linkedin id"

[params.colors]
  # hugo-dusk colors
  background = "#f5f5f5" # background color for the site
  main = "#e84848"
  text = "#444444"
  code-quote-bg = "" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
