# This is the configuration file for the example website of the Hugo theme
# Astatine (see https://github.com/hugcis/hugo-astatine-theme).
#
# The URL from which the site will be served
baseurl = "https://ljwolf.org/"
# Language used
languageCode = "en-us"
# Website title
title = "Yet Another Geographer"
# Theme used
theme = "hugo-astatine-theme"

preserveTaxonomyNames = true
rssLimit = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Taxonomies (only tags and categories are supported out of the box but you can
# add more)
[taxonomies]
    category = "categories"  
    tag = "tags"

# Configure permalinks style
[permalinks]
    post = "/:slug/"
    page = "/:slug/"

# Configure main navbar links. They can have a weight to select the order.
# This links to content within the content/post/ folder
[[menu.main]]
    name = "ORCID"
    url =  "https://orcid.org/0000-0003-0274-599X"
    weight = -180

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ljwolf" 
    weight = -170

[[menu.main]]
    name = "CV"
    url = "https://www.dropbox.com/scl/fi/47ze08ifgnxhme1d27k1p/currvita.pdf?rlkey=d5ujruhbwb6gevwhrakjinzo8&dl=0"
    weight = -160

[[menu.main]]
    name = "Blog"
    url = "https://blog.ljwolf.org"
    weight = -150

[[menu.main]]
    name = "Teaching"
    url = "/teaching"
    weight=-130


# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = """"""
    # Author of the site
    authorName = "Levi John Wolf"
    # Main image for the author. This will be the default image for SEO.
    [params.imgname]
        name = "images/main.jpg"
        # Add an alt description for the image
        alt = "Profile picture"

    # Indicate if you host Katex yourself. Defaults to using the CDN KaTex.
    # hostedKaTex = false

    # Optional: add a twitter handle and mastodon handle for SEO.
    [params.twitter]
        name = "@levijohnwolf"

    [params.bsky]
        name = "@levijohnwolf"

    [params.github]
        name = "ljwolf"

    [params.orcid]
	name="0000-0003-0274-599X"

    # [params.mastodon]
        # name = "@jkharkness"
        # host = "mastodon.social"
    
    # Enable link to feed in footer
    blogrss = true

    # Enable pingback and webmention via webmention.io
    # webmention = "hugocisneros.com"


# Sitemap location (default is /sitemap.xml)
[sitemap]
  filename = "sitemap.xml"
