baseurl = "/posts/"
title = "Yet Another Geographer"
copyright = ""
languageCode = "en-US"
canonifyurls = true
paginate = 3
theme = "dusk"

googleAnalytics = ""
disqusShortname = ""

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "monokai" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[author]
  name = ""

[params.meta]
  keywords = ""
  description = "Personal blog."

[params]
  email = "myemail"
  github = "github id"
  #gitlab = "gitlab id"
  twitter = "twitter id"
  #linkedin = "linkedin id"

[params.colors]
  # hugo-dusk colors
  background = "#f5f5f5" # background color for the site
  main = "#e84848"
  text = "#444444"
  code-quote-bg = "" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
