---
title: "What do you mean?"
output:
  tufte::tufte_html: default
  tufte::tufte_handout: default
---

Today, we will use the *actual* sales prices of property listings in the WECA area The best answers will provide both useful visualizations and textual discussion of the correct answer. Code is also useful. In most cases, the answer can be provided in a line of code, a plot, and two or three sentences.  

# 1. Doing Data Science Mentally

Let's get you thinking about conditional probabilities.[^hint-conditionals]. To do this, read in the `sales.csv` data. If listing is:

## 1.1 
from 1999, what's your best guess as to the price of that house?

## 1.2
about a *detached house* in 1999, what's your best guess as to the price of that house?  

## 1.3
for a flat, is it likely to be sold as a freehold or leasehold?

## 1.4 
for a detached house, is it likely to be sold as a freehold or leasehold? 

## 1.5
pricier than 500000,  is it likely to be sold as a freehold or leasehold?

# 2. A Linear Model

Fit a linear model that predicts listing price using a unique mean in each year.[^hint-factors] Interpreting this model:

## 2.1
Which years are *not* "statistically significant?" Why might this be the case?

## 2.2
What's the model's prediction of listing price in 1999? How does this compare to your guess from section 1?

## 2.3
Are there any issues with the model that you can identify? [^hint-bias]

# 3. Getting Nonlinear

## 3.1 
Fit a *generalized* linear model that predicts whether a listing is a freehold using the price of the listing.

## 3.2
According to the model, do more expensive listings tend to be freehold properties? 

## 3.3
Make a histogram of the predicted probability that a listing is freehold.[^hint-logit] Describe this histogram. 

## 3.4
Using `table(actual, predicted)`, build some [confusion matrices](https://en.wikipedia.org/wiki/Confusion_matrix#Table_of_confusion) that describes your prediction errors when you use three different cutoffs:

- $\hat{p}>.5$ means a house is a freehold.
- $\hat{p}>.75$ means a house is a freehold.
- $\hat{p}>.99$ means a house is a freehold.

## 3.5
Of the cutoffs above, which gives the lowest number of mis-classified observations? 

## 3.6 Challenge

For a few different thresholds, compute the true positive and false positive rate. This trade-off between false positives and true positives is the core concept behind the Receiver Operating Characteristic Curve (ROC Curve)^[Check ISL, p. 147 for a brief explanation.] Using the `plotROC` package, try making a ROC plot. 
    
# 4. Thinking through what all this means

Using your model from the previous question

## 4.1 
Go back to your analyses in part 1.4. What percentage of the other house types are freehold or leasehold? Is there an issue with confounding in your model from section 3? 

## 4.2 
Fit a new model predicting whether or not a listing is a freehold property using its price *and* its property type. Do your conclusions about price and freehold status still hold? 

[^hint-conditionals]: These can all be done easily with `filter()` and `group_by`.
[^hint-factors]: Be careful! In this model, are `years` numbers or categories? 
[^hint-bias]: There are three things I would keep in mind here. First, recall that you can use the `residuals(model)` function to extract your model prediction errors and you can also get predictions using `predict(model)`. Second, you may find it useful to create columns containing model predictions or errors. Finally, remember the typical issues that models can have, such as heteroskedasticity or bias when predictions are grouped in a way the model ignores. 
[^hint-lag]: just like the `first()` and `last()` functions used in the last assignment, the `lag()` and `lead()` functions get the previous (or the next) group's values in a group-by.
[^hint-logit]: Remember: the prediction for a logistic model is a *logit* value by default. Set the `type` option to `"response"` in the `predict` function to get predicted *probabilities*. 
