---
title: "Getting on another level"
output:
  tufte::tufte_html: default
  tufte::tufte_handout: default
---

Today, we'll use the `earnings` data on the relationship between race, height, sex, age, and earnings. The data is expressed as:

1. `earnings`, the yearly earnings (in $1000) for workers in a study
2. `height`, height in meters of the participant 
3. `sex`, one of `male`,`female`
4. `race`, racial category from the US Census, one of `white`, `black`, `asian`, `native`, `other`
5. `education`, the highest level of education attempted, one of `none`, `primary`, `secondary`, `university`, `postgraduate`, `phd`
6. `is_hispanic`, binary variable indicating whether the respondent identifies as a hispanic ethnicity
7. `age`, the age of the respondent. Must be over 18 to have participated in the study. 
8. `age_band`, a categorical variable indicating whether the respondent is 18 to 34, 35 to 50, or 50+. 
9. `was_promoted`, a categorical variable indicating whether the respondent was promoted recently. 

# 1

Fit three separate simple linear regressions, one predicting earnings by height for all the data, one that predicts earnings using height *only among men*, and another that predicts earnings using height *only among women*.

## 1.1 
Does an extra meter of height have a statistically significant impact on earnings among men? How about among women? Are the impacts *significantly different* in the two models?[^hint-comparison]

## 1.2

Why would the impact of height on earnings be  *so much larger* for the data overall than for men or women as a subset?[^hint-scatter]

## 1.3 
Fit a fixed effect model so that men and women have different baseline earnings, but so that height has the same effect on men and women. Does this give you a more reasonable estimate of the effect of height on earnings? Also, according to your regression: what is the difference in earnings for a 1.75 meter man vs. a 1.75 meter woman? 

## 1.4

Fit a multilevel model using `lmer` that allows both the baseline earnings and the impact of height on earnings to vary by sex. Show me the table of estimates using `tidy`.[^hint-broommixed] How does this compare to your regressions from earlier in this section?

# 2

## 2.1 

Fit a *generalized* mixed-effect model that predicts whether a respondent has income[^hint-hasincome], depending on their sex. Allow both the intercept and the effect of sex to vary by education level. 

## 2.2

What are the fixed and random component estimates for the model? 


## 2.3

What is the *predicted probability* a respondent in each group having their earnings recorded?[^hint-expandgrid] 

## 2.4

Interpreting the table from the previous question, which levels of education have the largest difference between men and women in the probability an income is recorded, and which levels have the smallest? Why do you think this pattern occurs? 

## 2.5 Challenge

What is the best ``cutoff'' to accurately predict whether a respondent has income? Show me the confusion matrix for this cutoff. 

[^hint-comparison]: Remember that questions about statistical significance can be answered by *confidence intervals*, not just the $p$-values. 
[^hint-scatter]: It also may help to build a scatterplot of the earnings vs. height with the regression lines you've just fit. Remember that you can use `geom_smooth(..., method=lm)` to plot the line of best fit. And, you can specify a new `aes()` for each `geom_` element in your `ggplot`. 
[^hint-hasincome]: It will help to build a new column in your dataframe that is zero where income is zero or NA and is 1 elsewhere. You might want to do this first by finding where the income is larger than zero and *then* filling in missing values using `replace_na`. 
[^hint-expandgrid]: Using `tidyr::expand_grid`, you can build a dataframe of all the combinations of two vectors quickly. For example, you could describe most rooms in the university with `tidyr::expand_grid(`
`floor=c("carpet", "tile","linoleum"),`
`walls=c("paint","wood paneling"))`
[^hint-broommixed]: Since these are mixed effect models, make sure you have the `broom.mixed` package installed!